services:
  - type: web
    name: gmsystem-frontend
    env: static
    buildCommand: npm run build:deploy
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
