services:
  - type: web
    name: gmsystem-frontend
    env: static
    buildCommand: npm run build:deploy
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
      - type: rewrite
        source: /advisor/*
        destination: /index.html
      - type: rewrite
        source: /student/*
        destination: /index.html
      - type: rewrite
        source: /secretary/*
        destination: /index.html
      - type: rewrite
        source: /student-affairs/*
        destination: /index.html
      - type: rewrite
        source: /deans-office/*
        destination: /index.html
